etl:
    output: ENC[AES256_GCM,data:ysQUZuDytUWkDO0N+/aySBJFNcd42Jek5eGoSgtf+zDmLZ7ZwTn6teN+KKz6cgXllm7gdnD4ed4=,iv:H9coycFZ8cFQTJtBDMLu/B3JHZqVNCzVmL+zjZHQQk4=,tag:RgYEyTY1WjBvJpJAJ9wmhg==,type:str]
    providerURI: ENC[AES256_GCM,data:OXI2Q8RqR8Wj4Fl+BUDDP00XwZzAzkC5ecdS1g==,iv:oaERXy8gfS64Pu3d/1OqdOzewUhEAaECLCvBC2D966Q=,tag:fDpY21BIJKo6GhspCQIKrw==,type:str]
    kafka:
        cluster_name: ENC[AES256_GCM,data:yx3FMH48Ko2Jet4nuhVcm6bOY2Q=,iv:qPT7D/IafXKWlQV5Fn/DOlwdA7xUzVFRasgcEa+Ipls=,tag:AYfmHSSzEjlR/byF57cLmA==,type:str]
        cluster_namespace: ENC[AES256_GCM,data:yQeA5hP4ETGouw==,iv:3zYUpWvlvIm75tuR+7TXWtJXPmMsr7QdZLmKujtRCIc=,tag:OLh361cs7+OHrAGRZyQFNw==,type:str]
        schemaRegistry:
            enabled: ENC[AES256_GCM,data:5VGlvQ==,iv:loQajPS4OVaINQe6kFPgHbOQwpNYfLDg25pzTpmrPj8=,tag:OvwhuJzbfmeqNnhEd6QaMw==,type:bool]
            url: ENC[AES256_GCM,data:2xt+mylkqSMsOhXsW0v+ChYV8fcor8wBEaGWwAv11F6qUPvQpuXGGXcW/hV3yrdZaT+K8YyTT1zE8FA30A==,iv:bn0vrEd4mFR3hycIhA5EoMW9kEMIrtDPx4QDuwt97is=,tag:Np1KJ4ONFO6v7tnfxUCLjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
        - vault_address: https://vault.geometry-dev.net:8200
          engine_path: sops
          key_name: dev-us-west-2
          created_at: "2021-07-26T19:57:21Z"
          enc: vault:v1:B+TeEPvgsL3g0QfXISGOgOlQ0Gv0Wc/6xms7IaSPcCaQQwEjDAGrosPB6dPje8Qh/e/mtXwGBkNyqb1L8dJKNhtZxvmkVBARIcMcCQZeXslR1sh3y/eIzKCm1UQxzWmB9c2HHNyKIzg8KqIQ6J+gaBoPND6zZw0mmsPboSouVShy1mqldiYLZQRR4Ryk07oNAyx3U4ryNumqiXVFoieNn5gs7L1C/WhpeQscK5uSvxSkWt1j9pHJDPu8y0/4Lpx2M+DJ3O50MiTs9pCe659AYWiEsYJ/77FQ0PSVUomlLiMoJlc275KiJI7xvy5q70gTaayWXQf7OoGT+WT78vX+v96PtaKWux3CUreEeChRfjpXkLByQ/vNhtHql0SXgHhpZy+M8p44MMmLxHHgqQXxIyN0Lbkj/CRaGWSDfqvuT26T8oNKTAdp72VjbzvVDAfg4CV0dBGkRlMfG4xPAtA9M/CwGxuG4uoal0/WeAnrExlah77C26yO/hmi8KDLwflP4L1OMMyWDP4MCK+YLaY18c0bJ40DjxgMY5x5E0XZLXIb+rLvj81MAWdRkOWOTp+UVAkwdMIv7DFCTzUT5YRLpEBv7Vey5XOUpE1Uq64ZEkPt1Qc3O35H/0YvhPc8fNm+rsNRiFEk63GEEmZdryf01/Q6vyiTyBhXwUNF7U523Tc=
    age: []
    lastmodified: "2021-09-28T13:51:27Z"
    mac: ENC[AES256_GCM,data:/H6F4grPG+oEHeDzCtO9NjGcAXvL8C2CHW0ayAXw0yjL2+2TjfAzZSG1FcHEwY//nPwZjhLyogCnWdU+90uMuRp9i7KBGlldMBTOldFmMDv7P/qZNUCApKwj37cPCe7EM+HSzihAJORuSNlR60nqRLdTN8PNTqKMGSIKIsX+qc4=,iv:aSgZ53mWEbwv8dpJSf3br8KOnCX6WyVKz3q+YUdK2gY=,tag:h/SGlOiCEPMQGUGdkpRwXA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
