deployment:
  replicas: 1
  annotations: |
    'consul.hashicorp.com/connect-inject': 'true'
    'consul.hashicorp.com/connect-service-upstreams': 'icon-nodes-mainnet-b:9000'
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
image:
  repository: geometrylabs/iconetl
  tag: "v0.1.5-alpha.2"
  imagePullPolicy: IfNotPresent

etl:
  mode: stream
  startAtHead: false
  startBlock: "40000000"
  kafka:
    strimzi_enabled: false
    topics:
      blocks:
        name: v015a-blocks-raw
      transactions:
        name: v015a-transactions-raw
      logs:
        name: v015a-logs-raw
