name: Release to CI

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
    paths-ignore:
      - 'charts/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Test
        id: docker_test
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          target: test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Tag name
        id: source
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          target: prod
          push: true
          tags: |
            geometrylabs/iconetl:latest
            geometrylabs/iconetl:${{ steps.source.outputs.TAG }}

  update_deployments:
    name: Update dev deployments
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Merge main -> deployment-dev-head
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: deployment-dev-head
          github_token: ${{ github.token }}

      - name: Merge main -> deployment-dev-backfill
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: deployment-dev-backfill
          github_token: ${{ github.token }}

      - name: Checkout dev head deployment
        uses: actions/checkout@v2
        with:
          ref: deployment-dev-head
          path: deployment-dev-head

      - name: Checkout dev backfill deployment
        uses: actions/checkout@v2
        with:
          ref: deployment-dev-backfill
          path: deployment-dev-backfill

      - name: Update dev head deployment values file and re-commit
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'chart/deployments/dev-mainnet-head/values.dev.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.source.outputs.TAG }}
          branch: deployment-dev-head
          createPR: 'false'
          token: ${{ secrets.GITHUB_TOKEN }}
          updateFile: true
          workDir: deployment-dev-head

      - name: Update dev backfill deployment values file and re-commit
        uses: fjogeleit/yaml-update-action@master
        with:
          valueFile: 'chart/deployments/dev-mainnet-backfill/values.dev.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.source.outputs.TAG }}
          branch: deployment-dev-backfill
          createPR: 'false'
          token: ${{ secrets.GITHUB_TOKEN }}
          updateFile: true
          workDir: deployment-dev-backfill