name: Release to CI

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
    paths-ignore:
      - 'charts/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Test
        id: docker_test
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          target: test

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Tag name
        id: source
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          target: prod
          push: true
          tags: |
            geometrylabs/iconetl:latest
            geometrylabs/iconetl:${{ steps.source.outputs.TAG }}

  update_deployments:
    name: Update deployments
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout charts repo
        uses: actions/checkout@v2
        with:
          repository: geometry-labs/icon-charts
          ref: main
          path: charts
          token: ${{ secrets.ICON_CHARTS_PAT }}

      - name: Update dev values file
        uses: fjogeleit/yaml-update-action@master
        with:
          workDir: charts
          repository: geometry-labs/icon-charts
          valueFile: 'deployments/dev/mainnet/etl/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.source.outputs.TAG }}
          branch: main
          createPR: 'false'
          updateFile: true
          commitChange: false

      - name: Update prod mainnet us-west values file
        uses: fjogeleit/yaml-update-action@master
        with:
          workDir: charts
          repository: geometry-labs/icon-charts
          valueFile: 'deployments/prod-us-west-2/mainnet/etl/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.source.outputs.TAG }}
          branch: main
          createPR: 'false'
          updateFile: true
          commitChange: false

      - name: Update prod sejong us-west values file
        uses: fjogeleit/yaml-update-action@master
        with:
          workDir: charts
          repository: geometry-labs/icon-charts
          valueFile: 'deployments/prod-us-west-2/mainnet/etl/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.source.outputs.TAG }}
          branch: main
          createPR: 'false'
          updateFile: true
          commitChange: false

      - name: Update prod mainnet eu-west values file
        uses: fjogeleit/yaml-update-action@master
        with:
          workDir: charts
          repository: geometry-labs/icon-charts
          valueFile: 'deployments/prod-eu-west-1/mainnet/etl/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ steps.source.outputs.TAG }}
          branch: main
          createPR: 'false'
          updateFile: true
          commitChange: false

      - name: Configure credentials
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.ICON_CHARTS_PAT }}'
          global: true
          name: 'Geometry Bot'
          email: '78675928+geometrybot@users.noreply.github.com'

      - name: Commit all updates
        run: |
          git add -A
          git commit -m "ETL deployment image versions to ${{ steps.source.outputs.TAG }}"
          git push origin
        working-directory: charts

      - name: Push tags
        run: |
          git stash
          git pull
          git tag -f etl-prod-uswest2 ${{ steps.yaml-update.outputs.commit }}
          git tag -f etl-prod-euwest1 ${{ steps.yaml-update.outputs.commit }}
          git push -f origin --tags
        working-directory: charts